FROM sulhan/arch-base:latest
MAINTAINER Sulhan <ms@kilabit.info>

ExPOSE 5432
VOLUME ["/var/lib/postgres"]

COPY init.sh /
COPY postgresql.conf /
COPY pg_hba.conf /
COPY bootstrap.sh /

RUN exec /bootstrap.sh

CMD ["/init.sh"]
