FROM sulhan/arch-base:latest
MAINTAINER Sulhan <ms@kilabit.info>

EXPOSE 5432

COPY bootstrap.sh /
COPY init.sh /

COPY *.db /var/lib/pacman/sync/
COPY *.xz /var/cache/pacman/pkg/

RUN exec /bootstrap.sh

VOLUME ["/var/lib/postgres"]

CMD ["/init.sh"]
