FROM sulhan/arch-base:latest
MAINTAINER Sulhan <ms@kilabit.info>

COPY *.db /var/lib/pacman/sync/
COPY *.xz /var/cache/pacman/pkg/

EXPOSE 80

COPY bootstrap.sh /

RUN exec /bootstrap.sh

CMD ["/bin/bash"]
